In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("datasets/iris/iris.csv")
data.head(4)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa

In [3]:
#comma separattori
data2 : pd.DataFrame = pd.read_csv("datasets/health/health_v1.csv", na_values="NaN", sep=";", low_memory=False )
data2.head(5)

   ID  Weight  Smoking Exercise Cholesterol Income  Happiness BirthYear Sex
0   1    75.0      0.0        3         5,8   3230       59.0      1964   1
1   2    70.0      0.0        6         5,9   1420       43.0      1952   1
2   3    76.0      0.0        6           6   4930       74.0      1951   1
3   4    62.0      0.0        8         4,7   2970       58.0      1959   1
4   5    44.0      0.0        8         4,3   4780       64.0      1925   1

In [4]:

'''Datatyypit dataframessa:'''
data2.dtypes

ID               int64
Weight         float64
Smoking        float64
Exercise           str
Cholesterol        str
Income             str
Happiness      float64
BirthYear          str
Sex                str
dtype: object

In [5]:
#Smoking arrayn uniikit arvot
data2.Smoking.unique()

array([ 0.,  1., nan])

In [6]:
#DataFrame on dict?
data2["Smoking"]

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
995    1.0
996    1.0
997    0.0
998    1.0
999    0.0
Name: Smoking, Length: 1000, dtype: float64

In [13]:
#Tämä ei muokkaa alkuperäistä DataFramea
data2.Smoking.replace(1.0, 0.0)
# Jos haluaa muokata alkuperäistä laittaa argumentin replace(1,0, inplace=True)

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
995    1.0
996    1.0
997    0.0
998    1.0
999    0.0
Name: Smoking, Length: 1000, dtype: float64

In [14]:
data2.Smoking

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
995    1.0
996    1.0
997    0.0
998    1.0
999    0.0
Name: Smoking, Length: 1000, dtype: float64

In [19]:
# &-merkkiä voi käyttää AND operaattorina filtterissä

data2[(data2["Smoking"] == 1.0) & (data2.Happiness > 60)]

,ID,Weight,Smoking,Exercise,Cholesterol,Income,Happiness,BirthYear,Sex
58,59,82.0,1.0,3,6,4610,61.0,1955,1
144,145,73.0,1.0,3,"7,6",4090,66.0,1932,2
197,198,83.0,1.0,6,"5,9",2210,70.0,1968,1
235,236,72.0,1.0,6,"6,1",2720,73.0,1925,2
272,273,88.0,1.0,6,"4,6",4340,85.0,1974,2
300,301,73.0,1.0,7,"6,2",3110,79.0,1972,2
304,305,81.0,1.0,5,"5,1",1850,61.0,1942,2
351,352,84.0,1.0,5,"5,3",3480,62.0,1959,2
414,415,73.0,1.0,6,"6,1",3340,75.0,1953,Female
446,447,102.0,1.0,2,"6,5",2170,64.0,1945,2
448,449,76.0,1.0,8,"3,9",4740,73.0,1965,2
530,531,84.0,1.0,3,"6,8",4840,68.0,1951,1
587,588,105.0,1.0,4,"7,5",2930,63.0,1973,2
599,600,98.0,1.0,0,"7,1",6050,63.0,1978,2
608,609,73.0,1.0,7,4,4360,81.0,1961,1
623,624,82.0,1.0,5,"5,3",3860,93.0,1953,2
692,693,90.0,1.0,3,"5,8",4150,61.0,1955,2
756,757,82.0,1.0,6,3,3550,95.0,1971,2
915,916,68.0,1.0,5,"6,1",4980,67.0,1931,2
981,982,79.0,1.0,4,"6,8",5550,77.0,1915,2
993,994,79.0,1.0,5,"5,2",4810,77.0,1955,2

In [2]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
chronic_kidney_disease = fetch_ucirepo(id=336)

# data (as pandas dataframes)
X = chronic_kidney_disease.data.features
y = chronic_kidney_disease.data.targets

# metadata
print(chronic_kidney_disease.metadata)

# variable information
print(chronic_kidney_disease.variables)

{'uci_id': 336, 'name': 'Chronic Kidney Disease', 'repository_url': 'https://archive.ics.uci.edu/dataset/336/chronic+kidney+disease', 'data_url': 'https://archive.ics.uci.edu/static/public/336/data.csv', 'abstract': 'This dataset can be used to predict the chronic kidney disease and it can be collected from the hospital nearly 2 months of period.', 'area': 'Other', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 400, 'num_features': 24, 'feature_types': ['Real'], 'demographics': ['Age'], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 2015, 'last_updated': 'Mon Mar 04 2024', 'dataset_doi': '10.24432/C5G020', 'creators': ['L. Rubini', 'P. Soundarapandian', 'P. Eswaran'], 'intro_paper': None, 'additional_info': {'summary': 'We use the following representation to collect the dataset\r\n                        age\t\t-\tage\t\r\n\t\t\tbp\t\t-\tblood pressure\r\n\t\t\tsg\t\t-\tspecific gravity\r\n\t\t\tal\t\t-   \talbumin\r\n\t\t\tsu\t\t-\tsugar\r\n\t\t\trbc\t\t-\tred blood cells\r\n\t\t\tpc\t\t-\tpus cell\r\n\t\t\tpcc\t\t-\tpus cell clumps\r\n\t\t\tba\t\t-\tbacteria\r\n\t\t\tbgr\t\t-\tblood glucose random\r\n\t\t\tbu\t\t-\tblood urea\r\n\t\t\tsc\t\t-\tserum creatinine\r\n\t\t\tsod\t\t-\tsodium\r\n\t\t\tpot\t\t-\tpotassium\r\n\t\t\themo\t\t-\themoglobin\r\n\t\t\tpcv\t\t-\tpacked cell volume\r\n\t\t\twc\t\t-\twhite blood cell count\r\n\t\t\trc\t\t-\tred blood cell count\r\n\t\t\thtn\t\t-\thypertension\r\n\t\t\tdm\t\t-\tdiabetes mellitus\r\n\t\t\tcad\t\t-\tcoronary artery disease\r\n\t\t\tappet\t\t-\tappetite\r\n\t\t\tpe\t\t-\tpedal edema\r\n\t\t\tane\t\t-\tanemia\r\n\t\t\tclass\t\t-\tclass\t', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'We use 24 + class = 25 ( 11  numeric ,14  nominal)\r\n1.Age(numerical)\r\n  \t  \tage in years\r\n \t2.Blood Pressure(numerical)\r\n\t       \tbp in mm/Hg\r\n \t3.Specific Gravity(nominal)\r\n\t  \tsg - (1.005,1.010,1.015,1.020,1.025)\r\n \t4.Albumin(nominal)\r\n\t\tal - (0,1,2,3,4,5)\r\n \t5.Sugar(nominal)\r\n\t\tsu - (0,1,2,3,4,5)\r\n \t6.Red Blood Cells(nominal)\r\n\t\trbc - (normal,abnormal)\r\n \t7.Pus Cell (nominal)\r\n\t\tpc - (normal,abnormal)\r\n \t8.Pus Cell clumps(nominal)\r\n\t\tpcc - (present,notpresent)\r\n \t9.Bacteria(nominal)\r\n\t\tba  - (present,notpresent)\r\n \t10.Blood Glucose Random(numerical)\t\t\r\n\t\tbgr in mgs/dl\r\n \t11.Blood Urea(numerical)\t\r\n\t\tbu in mgs/dl\r\n \t12.Serum Creatinine(numerical)\t\r\n\t\tsc in mgs/dl\r\n \t13.Sodium(numerical)\r\n\t\tsod in mEq/L\r\n \t14.Potassium(numerical)\t\r\n\t\tpot in mEq/L\r\n \t15.Hemoglobin(numerical)\r\n\t\themo in gms\r\n \t16.Packed  Cell Volume(numerical)\r\n \t17.White Blood Cell Count(numerical)\r\n\t\twc in cells/cumm\r\n \t18.Red Blood Cell Count(numerical)\t\r\n\t\trc in millions/cmm\r\n \t19.Hypertension(nominal)\t\r\n\t\thtn - (yes,no)\r\n \t20.Diabetes Mellitus(nominal)\t\r\n\t\tdm - (yes,no)\r\n \t21.Coronary Artery Disease(nominal)\r\n\t\tcad - (yes,no)\r\n \t22.Appetite(nominal)\t\r\n\t\tappet - (good,poor)\r\n \t23.Pedal Edema(nominal)\r\n\t\tpe - (yes,no)\t\r\n \t24.Anemia(nominal)\r\n\t\tane - (yes,no)\r\n \t25.Class (nominal)\t\t\r\n\t\tclass - (ckd,notckd)', 'citation': None}}
     name     role         type demographic              description  \
0     age  Feature      Integer         Age                      NaN
1      bp  Feature      Integer         NaN           blood pressure
2      sg  Feature  Categorical         NaN         specific gravity
3      al  Feature  Categorical         NaN                  albumin
4      su  Feature  Categorical         NaN                    sugar
5     rbc  Feature       Binary         NaN          red blood cells
6      pc  Feature       Binary         NaN                 pus cell
7     pcc  Feature       Binary         NaN          pus cell clumps
8      ba  Feature       Binary         NaN                 bacteria
9     bgr  Feature      Integer         NaN     blood glucose random
10     bu  Feature      Integer         NaN               blood urea
11     sc  Feature   Continuous         NaN         serum creatinine
12    sod  Feature      Integer         NaN                   sodium
13    pot  Feature   Continuous         NaN                potassium
14   hemo  Feature   Continuous         NaN               hemoglobin
15    pcv  Feature      Integer         NaN       packed cell volume
16   wbcc  Feature      Integer         NaN   white blood cell count
17   rbcc  Feature   Continuous         NaN     red blood cell count
18    htn  Feature       Binary         NaN             hypertension
19     dm  Feature       Binary         NaN        diabetes mellitus
20    cad  Feature       Binary         NaN  coronary artery disease
21  appet  Feature       Binary         NaN                 appetite
22     pe  Feature       Binary         NaN              pedal edema
23    ane  Feature       Binary         NaN                   anemia
24  class   Target       Binary         NaN           ckd or not ckd

           units missing_values
0           year            yes
1          mm/Hg            yes
2            NaN            yes
3            NaN            yes
4            NaN            yes
5            NaN            yes
6            NaN            yes
7            NaN            yes
8            NaN            yes
9         mgs/dl            yes
10        mgs/dl            yes
11        mgs/dl            yes
12         mEq/L            yes
13         mEq/L            yes
14           gms            yes
15           NaN            yes
16     cells/cmm            yes
17  millions/cmm            yes
18           NaN            yes
19           NaN            yes
20           NaN            yes
21           NaN            yes
22           NaN            yes
23           NaN            yes
24           NaN             no